{
 "title": "Accounts - Epos Transfer",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Successful Transfers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "metricName": "ProcessingSuccessCount",
     "namespace": "live-processing-metrics",
     "period": "1d",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Missing Tenders",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "metricName": "MissingTenderWarningCount",
     "namespace": "live-processing-metrics",
     "period": "1d",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Transfer Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "metricName": "ProcessingErrorCount",
     "namespace": "live-processing-metrics",
     "period": "1d",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Transactions Per Day",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "metricName": "ProcessingSuccessCount",
     "namespace": "live-processing-metrics",
     "period": "1d",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "metricName": "ProcessingSkipCount",
     "namespace": "live-processing-metrics",
     "period": "1d",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "metricName": "ProcessingErrorCount",
     "namespace": "live-processing-metrics",
     "period": "1d",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Epos Transfer Errors",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expression": "filter @message like /Exception|ERROR/\n| fields @timestamp, @message\n| sort @timestamp desc\n| limit 20",
     "logGroupNames": [
      "/aws/lambda/live-transaction-sqs-lambda"
     ],
     "queryMode": "Logs",
     "region": "default"
    }
   ]
  }
 ]
}