name: Deploy on PR merge
on:
  push:
    branches:
      - main
jobs:
  deploy-live-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Get Terraform version
        id: getterraformversion
        run: echo "::set-output name=version::$(cat terraform/.terraform-version)"
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ steps.getterraformversion.outputs.version }}
          cli_config_credentials_token: ${{ secrets.TF_TOKEN }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew clean build sonarqube --info -x test

      - name: Build Zip
        run: ./gradlew buildZip

      - name: Copy live ZIP to S3
        run: |
          aws s3 cp build/distributions/accounts.zip s3://mcc-accounts-deployment/live-accounts.zip
      - name: Deploy bootstrap Terraform
        working-directory: terraform/bootstrap
        run: |
          terraform init -input=false

          terraform apply -auto-approve

      - name: Deploy live build to AWS
        working-directory: terraform/environment
        env:
          TF_TOKEN: ${{ secrets.TF_TOKEN }}
        run: |
          mv test-mappings.auto.tfvars test-mappings.tfvars
          mv live-mappings.tfvars live-mappings.auto.tfvars
          terraform init -input=false \
            -backend-config=live-backend.hcl

          terraform apply -auto-approve
